name: build-debug-GKI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
    - name: Remove Useless Package
      run: |
        docker_images="$(docker images -q)"
        [ -n "$docker_images" ] && docker rmi "$docker_images"
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt-get -y autoremove --purge
        sudo apt-get -y autoclean
        sudo apt-get clean

    - name: Free Disk Space Before Build
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        echo "Disk space after cleanup:"
        df -h

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 3072
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        # remove-android: 'true'

    - name: Sync Repo
      run: |
        export HOME=${GITHUB_WORKSPACE}
        mkdir -p $HOME/.local/bin
        export PATH=$HOME/.local/bin:$PATH
        wget -O $HOME/.local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+rx $HOME/.local/bin/repo

        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "GKI-Action-Build-Bot"
        git config --global user.email "Android@teio.tk"

        repo init -u https://android.googlesource.com/kernel/manifest \
          -b common-android12-5.10-2024-05 --depth=1
        df -h

        ## Downloaded from https://ci.android.com/builds/submitted/13001810/kernel_aarch64/latest  -- manifest_13001810.xml
        cat > .repo/manifests/default.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <manifest>
        <remote name="aosp" fetch="https://android.googlesource.com/" review="https://android.googlesource.com/"/>
        <default revision="master-kernel-build-2021" remote="aosp" sync-j="4"/>
        <superproject name="kernel/superproject" remote="aosp" revision="common-android12-5.10-2024-05"/>
        <project path="build" name="kernel/build" clone-depth="1" revision="dbfab7e0de2e04316b526ef938b1140d7a5fd40d"/>
        <project path="hikey-modules" name="kernel/hikey-modules" revision="6f0a2a72f849d8bb8e708587582c20019ef91a3c" upstream="android12-5.10" dest-branch="android12-5.10"/>
        <project path="common" name="kernel/common" clone-depth="1" revision="9e4ccf17ac6332614a89a41fe2272be316369169" upstream="deprecated/android12-5.10-2024-05" dest-branch="deprecated/android12-5.10-2024-05"/>
        <project path="kernel/tests" name="kernel/tests" revision="c2ea6143e8f1efb9a68cca88159210e16cde1bac"/>
        <project path="kernel/configs" name="kernel/configs" revision="c10b7ea022edc356d37c092d7ca46bcb860f8a90"/>
        <project path="common-modules/virtual-device" name="kernel/common-modules/virtual-device" revision="9b39747550f44621e28d766f566ca96855e00865" upstream="android12-5.10" dest-branch="android12-5.10"/>
        <project path="prebuilts-master/clang/host/linux-x86" name="platform/prebuilts/clang/host/linux-x86" clone-depth="1" revision="6e3223f76384455acde43affde3df0ea9df66c0d"/>
        <project path="prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8" name="platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8" clone-depth="1" revision="4e6f66acf138d40d9a80be24b275abb9c6eed729"/>
        <project path="prebuilts/build-tools" name="platform/prebuilts/build-tools" clone-depth="1" revision="cfedc16ec3deb680fca6fe2aff44a1837a97b50d"/>
        <project path="prebuilts/kernel-build-tools" name="kernel/prebuilts/build-tools" clone-depth="1" revision="ca5b087f88c0302ff66f59a6f26be663e92baf15"/>
        <project path="tools/mkbootimg" name="platform/system/tools/mkbootimg" revision="34bc8bfb493401f7aadbd3b434f9fbfa521e9301"/>
        </manifest>
        EOF
        # tree -aF
        repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle
        ls -AlFh
        df -h

    - name: SuperUser Patch
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/common
        git config --global user.name "GKI-Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        curl -LsS "https://git.zx2c4.com/kernel-assisted-superuser/plain/fetch-and-patch.sh" | bash -

        sed -i -e "s/endmenu//" -e "s/---help---/help/" -e "$ a endmenu" drivers/base/Kconfig

        echo -e "\n\n#### drivers/base/Kconfig ####"
        cat drivers/base/Kconfig
        echo -e "\n\n#### drivers/base/Makefile ####"
        cat drivers/base/Makefile
        echo 'CONFIG_ASSISTED_SUPERUSER=y' >> arch/arm64/configs/gki_defconfig
        echo -e "\n\ngrep ASSISTED_SUPERUSER from arch/arm64/configs/gki_defconfig"
        cat arch/arm64/configs/gki_defconfig | grep ASSISTED_SUPERUSER
        echo 'CONFIG_ASSISTED_SUPERUSER=y' >> arch/arm64/configs/defconfig
        echo -e "\n\ngrep ASSISTED_SUPERUSER from arch/arm64/configs/defconfig"
        cat arch/arm64/configs/defconfig | grep ASSISTED_SUPERUSER
        [ -e drivers/base/superuser.c ] && echo "drivers/base/superuser.c exists" || echo "drivers/base/superuser.c does not exist"

    - name: Building
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        LTO=thin \
        KERNEL_BINARY=Image \
        BUILD_CONFIG=common/build.config.gki.aarch64 \
        build/build.sh
        ls -AlFh out/android12-5.10/dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Image.superuser
        path: workspace/out/android12-5.10/dist/Image
        if-no-files-found: error
