name: build-debug-GKI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env: 
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
    - name: Remove Useless Package
      run: |
        docker_images="$(docker images -q)"
        [ -n "$docker_images" ] && docker rmi "$docker_images"
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt-get -y autoremove --purge
        sudo apt-get -y autoclean
        sudo apt-get clean

    - name: Free Disk Space Before Build
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        echo "Disk space after cleanup:"
        df -h
  
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 3072
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'


    - name: Prepare Environment
      run: |
        df -h
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt-get -y install git curl repo python3 zip unzip flex bison \
          libssl-dev coreutils ccache clang llvm lld
        df -h

    - name: Sync Repo
      run: |
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "GKI-Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        repo init -u https://android.googlesource.com/kernel/manifest \
          -b common-android12-5.10-2024-05_r13 --depth=1
        repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle
        tree -aF -L 3

    - name: SuperUser Patch
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        curl -LsS "https://git.zx2c4.com/kernel-assisted-superuser/plain/fetch-and-patch.sh" | bash -
        echo 'CONFIG_ASSISTED_SUPERUSER=y' >> build.config.gki-debug.aarch64
        cat build.config.gki-debug.aarch64

    - name: Building
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        LTO=thin \
        KERNEL_BINARY=Image \
        BUILD_CONFIG=build.config.gki-debug.aarch64 \
        build/build.sh
        tree -aF -L 3

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: workspace/out/android12-5.10/dist/Image

